"""Agent: Save HTML exports for KPI Dashboard.

Isolates the "Save KPI Dashboard as Interactive HTML" logic that
previously lived inside agents/linkfms_fetch_app.py.

This agent builds a single self-contained HTML file embedding
Plotly figure HTML (full_html=False) and a simple KPI header.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Dict, Optional

from pathlib import Path

import plotly.io as pio


@dataclass
class KPIExportContext:
    plate_number: str
    start_date: str
    end_date: str
    timezone: str
    kpi_stats: Dict[str, Any]


def build_kpi_export_html(
    *,
    figs,
    ctx: KPIExportContext,
    html_title: str = "Vehicle KPI Dashboard",
) -> str:
    """Build the KPI dashboard HTML wrapper with embedded Plotly charts."""

    # figs can be a list of plotly figures or dict-like.
    if isinstance(figs, dict):
        figs_iter = list(figs.values())
    else:
        figs_iter = list(figs)

    charts_html = "".join(
        [
            pio.to_html(g, full_html=False, include_plotlyjs=("cdn" if i == 0 else False))
            for i, g in enumerate(figs_iter)
        ]
    )

    running_pct = ctx.kpi_stats.get("running_pct", 0.0)
    idle_pct = ctx.kpi_stats.get("idle_pct", 0.0)
    stopped_pct = ctx.kpi_stats.get("stopped_pct", 0.0)
    total_distance = ctx.kpi_stats.get("total_distance", 0.0)

    # Simple KPI card grid.
    kpi_cards = (
        "<div class='kpi-grid'>"
        "  <div class='kpi-card'><div class='kpi-title'>🏃 Running %</div>"
        f"    <div class='kpi-value'>{running_pct:.1f}%</div></div>"
        "  <div class='kpi-card'><div class='kpi-title'>⏸️ Idle %</div>"
        f"    <div class='kpi-value'>{idle_pct:.1f}%</div></div>"
        "  <div class='kpi-card'><div class='kpi-title'>⛔ Stopped %</div>"
        f"    <div class='kpi-value'>{stopped_pct:.1f}%</div></div>"
        "  <div class='kpi-card'><div class='kpi-title'>📍 Total Distance</div>"
        f"    <div class='kpi-value'>{total_distance:.1f} km</div></div>"
        "</div>"
    )

    html = f"""<!DOCTYPE html>
<html lang='en'>
<head>
<meta charset='utf-8'/>
<meta name='viewport' content='width=device-width, initial-scale=1'/>
<title>{html_title}</title>
<style>
:root{{--bg:#0b1220;--card:rgba(255,255,255,.06);--border:rgba(255,255,255,.12);--text:#eaf2ff;--muted:#9fb0d0;--accent:#7C3AED;}}
body{{margin:0;background:linear-gradient(135deg, #0EA5E9 0%, #7C3AED 55%, #F97316 100%);color:var(--text);font-family:Segoe UI,Arial,sans-serif;}}
.container{{max-width:1400px;margin:0 auto;padding:22px;}}
.header{{background:rgba(0,0,0,.25);border:1px solid var(--border);border-radius:16px;padding:18px 18px;box-shadow:0 18px 60px rgba(0,0,0,.25);text-align:center;}}
.header h1{{margin:0;font-size:28px;letter-spacing:.2px;}}
.header .sub{{margin-top:8px;color:rgba(255,255,255,.9);font-size:14px;}}
.kpi-grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:14px;margin:18px 0;}}
.kpi-card{{background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.14);border-radius:14px;padding:16px;box-shadow:0 10px 30px rgba(0,0,0,.15);}}
.kpi-title{{font-size:13px;color:var(--muted);margin-bottom:8px;}}
.kpi-value{{font-size:30px;font-weight:800;}}
.charts-section{{background:rgba(0,0,0,.18);border:1px solid var(--border);border-radius:16px;padding:16px;}}
.footer{{margin-top:14px;text-align:center;font-size:12px;color:rgba(255,255,255,.75);}}
</style>
</head>
<body>
<div class='container'>
  <div class='header'>
    <h1>📊 Vehicle Performance Report</h1>
    <div class='sub'>
      <span style='font-weight:700'>Plate:</span> {ctx.plate_number}&nbsp;&nbsp;
      <span style='font-weight:700'>Period:</span> {ctx.start_date} to {ctx.end_date}&nbsp;&nbsp;
      <span style='font-weight:700'>TZ:</span> {ctx.timezone}
    </div>
  </div>

  {kpi_cards}

  <div class='charts-section'>
    {charts_html}
  </div>

  <div class='footer'>Generated by LINKFMS Telemetry Analysis Tool</div>
</div>
</body>
</html>"""

    return html

