"""Agent: Save HTML exports for Visualize (Plotly figures).

This agent isolates the logic for the Streamlit UI button
"Save Generated Graphs as HTML" that currently lives inside
agents/linkfms_fetch_app.py.

It builds a single self-contained HTML string that embeds Plotly
figures using `plotly.io.to_html(..., full_html=False)`.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Tuple

import plotly.io as pio


@dataclass
class VisualizeExportContext:
    plate_number: str
    start_date: str
    end_date: str


def build_visualize_export_html(
    figs,
    *,
    html_title: str,
    charts_container_title: str = "Telemetry Report",
    ctx: Optional[VisualizeExportContext] = None,
) -> str:
    """Return an HTML string wrapping multiple Plotly figures."""

    charts_html = "".join(
        [
            pio.to_html(
                fig,
                full_html=False,
                include_plotlyjs=("cdn" if i == 0 else False),
            )
            for i, fig in enumerate(figs)
        ]
    )

    if ctx is None:
        plate_line = ""
        timeline_line = ""
    else:
        plate_line = f"<div class='pill'><b>Plate:</b> {ctx.plate_number}</div>"
        timeline_line = (
            f"<div class='pill'><b>Timeline:</b> {ctx.start_date} → {ctx.end_date}</div>"
        )

    return (
        "<!DOCTYPE html>\n"
        "<html lang='en'>\n"
        "<head>\n"
        "<meta charset='utf-8'/>\n"
        "<meta name='viewport' content='width=device-width, initial-scale=1'/>\n"
        f"<title>{html_title}</title>\n"
        "<style>\n"
        ":root{--bg0:#061021;--bg1:#0b1220;--text:#eaf2ff;--muted:#9fb0d0;--accent:#01696f;}\n"
        "body{margin:0;background:radial-gradient(1200px 600px at 20% 0%, rgba(96,165,250,.20), transparent 55%),\n"
        "radial-gradient(900px 500px at 90% 10%, rgba(34,197,94,.18), transparent 45%),\n"
        "linear-gradient(180deg,var(--bg0),var(--bg1));color:var(--text);font-family:Segoe UI,Arial,sans-serif;}\n"
        ".wrap{max-width:1200px;margin:0 auto;padding:20px;}\n"
        ".hero{background:linear-gradient(135deg, rgba(96,165,250,.22), rgba(34,197,94,.18));border:1px solid rgba(255,255,255,.08);\n"
        "border-radius:16px;box-shadow:0 18px 60px rgba(0,0,0,.35);padding:18px;}\n"
        ".hero h2{margin:0;font-size:20px;letter-spacing:.2px;}\n"
        ".meta{display:flex;flex-wrap:wrap;gap:10px;margin-top:10px;}\n"
        ".pill{background:rgba(255,255,255,.06);border:1px solid rgba(255,255,255,.10);border-radius:999px;padding:8px 12px;color:var(--muted);}\n"
        ".pill b{color:var(--text);}\n"
        ".grid{margin-top:18px;display:grid;gap:18px;}\n"
        ".card{background:linear-gradient(180deg, rgba(255,255,255,.06), rgba(255,255,255,.02));border:1px solid rgba(255,255,255,.08);border-radius:14px;padding:14px;box-shadow:0 14px 40px rgba(0,0,0,.25);}\n"
        "footer{margin-top:12px;color:rgba(234,242,255,.7);font-size:12px;}\n"
        "</style>\n"
        "</head>\n"
        "<body>\n"
        "<div class='wrap'>\n"
        "  <div class='hero'>\n"
        f"    <h2>📈 {charts_container_title}</h2>\n"
        "    <div class='meta'>\n"
        f"      {plate_line}\n"
        f"      {timeline_line}\n"
        "      <div class='pill'><b>Export:</b> HTML</div>\n"
        "    </div>\n"
        "  </div>\n"
        "  <div class='grid'>\n"
        "    <div class='card'>\n"
        f"      {charts_html}\n"
        "    </div>\n"
        "  </div>\n"
        "  <footer>Generated by LINKFMS Telemetry Analysis Tool</footer>\n"
        "</div>\n"
        "</body>\n"
        "</html>"
    )

